### ISSUE TITLE
Changelog doesn't mention the version '0.5.20161021'

### ISSUE THREAD

**Issue by nevinera** [knu/ruby-domain_name#10]
https://github.com/knu/ruby-domain_name/blob/master/CHANGELOG.md doesn't have an entry for the current release on rubygems, version '0.5.20161021'.

**Comment by PikachuEXE** [comment]
And the latest `0.5.20161129` too (and the tag for that is also missing)

**Comment by knu** [comment]
Somehow `rake release` did not push everything to GitHub, so I did it.

**Comment by nevinera** [comment]
Thanks!
