### ISSUE TITLE
git tag v0.6.20231109 is missing

### ISSUE THREAD

**Issue by tricknotes** [knu/ruby-domain_name#25]
Could you push tag `v0.6.20231109` as https://github.com/knu/ruby-domain_name/commit/d64fd2307f2796fd180b908666a782857b941525 ?
The URL https://github.com/knu/ruby-domain_name/tree/v0.6.20231109 is 404 documented in [CHANGELOG.md](https://github.com/knu/ruby-domain_name/blob/d64fd2307f2796fd180b908666a782857b941525/CHANGELOG.md).

**Comment by bastelfreak** [comment]
Hi @knu , any chance you could add the missing tag? I'm packaging the gem for Arch Linux and I need an up2date git tag to do so.

**Comment by knu** [comment]
Done!
