### ISSUE TITLE
Bad link on rubygems.org?

### ISSUE THREAD

**Issue by jaredbeck** [knu/ruby-domain_name#4]
1. Visit https://rubygems.org/gems/domain_name
2. Click "Source Code" link
3. Arrive at https://github.com/weppos/public_suffix_service

Is this intentional?  Should the link point here (https://github.com/knu/ruby-domain_name)?

**Comment by knu** [comment]
I have no idea how to fix that.

**Comment by jaredbeck** [comment]
> I have no idea how to fix that.

Neither do I, sorry.  It's not in your gemspec, AFAICT.  Maybe you have to log in to rubygems.org?

**Comment by jaredbeck** [comment]
Yeah, if you log in to rubygems.org and visit the page for your gem, there should be an "Edit" link, where you can edit a half-dozen URLs, including "Source Code URL".

**Comment by knu** [comment]
Oh, thanks for the tip.  I didn't even know I could log in to rubygems.org.  I'll try.

**Comment by knu** [comment]
Done!

**Comment by jaredbeck** [comment]
Thanks :)
